name: Javadoc

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew javadoc --no-daemon
    
    - name: Add and push
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "Automation"
        git add -v docs
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Javadocs" && git push -v
